"""Sends the daily Top-10 Dropship Winners email as a beautiful HTML report."""
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import date
from jinja2 import Template
from rich.console import Console

console = Console()

EMAIL_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Dropship Winners</title>
<style>
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
       background:#f4f4f0;margin:0;padding:24px;color:#1a1a1a}
  .wrapper{max-width:680px;margin:0 auto}
  .header{background:linear-gradient(135deg,#01696f,#0f3638);border-radius:16px;
          padding:32px 28px;color:#fff;margin-bottom:24px;text-align:center}
  .header h1{margin:0 0 6px;font-size:26px;font-weight:700}
  .header p{margin:0;opacity:.8;font-size:14px}
  .meta{display:flex;gap:16px;justify-content:center;margin-top:16px}
  .meta span{background:rgba(255,255,255,.15);border-radius:20px;
             padding:4px 14px;font-size:13px}
  .product-card{background:#fff;border-radius:12px;margin-bottom:16px;
                overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.07);
                display:flex;align-items:stretch}
  .rank-badge{background:#f7f6f2;min-width:52px;display:flex;align-items:center;
              justify-content:center;font-size:22px;font-weight:800;
              color:#01696f;border-right:1px solid #e8e6e0}
  .rank-badge.top3{background:#01696f;color:#fff}
  .product-img{width:90px;min-width:90px;object-fit:cover}
  .product-img-placeholder{width:90px;min-width:90px;background:#f0efeb;
                            display:flex;align-items:center;justify-content:center;
                            font-size:28px}
  .product-body{padding:14px 16px;flex:1}
  .product-title{font-size:14px;font-weight:600;margin:0 0 8px;
                 color:#1a1a1a;line-height:1.4}
  .scores{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:8px}
  .score-pill{border-radius:20px;padding:3px 10px;font-size:12px;font-weight:600}
  .winner{background:#e8f5e9;color:#2e7d32}
  .demand{background:#e3f2fd;color:#1565c0}
  .oppty{background:#fff3e0;color:#e65100}
  .platform-ali{background:#ffebee;color:#c62828}
  .platform-amz{background:#fff8e1;color:#f57f17}
  .breakdown{font-size:12px;color:#777;margin:0}
  .cta{display:inline-block;margin-top:8px;padding:6px 14px;
       background:#01696f;color:#fff;border-radius:6px;
       font-size:12px;font-weight:600;text-decoration:none}
  .footer{text-align:center;color:#aaa;font-size:12px;margin-top:24px;
          padding-top:16px;border-top:1px solid #e0ddd8}
  @media(max-width:480px){.product-card{flex-direction:column}
    .rank-badge{min-width:auto;padding:10px;font-size:18px;border-right:none;
                border-bottom:1px solid #e8e6e0}
    .product-img,.product-img-placeholder{width:100%;height:140px}}
</style>
</head>
<body>
<div class="wrapper">
  <div class="header">
    <h1>🏆 Top {{ products|length }} Dropship Winners</h1>
    <p>Daily automated scan across AliExpress &amp; Amazon</p>
    <div class="meta">
      <span>📅 {{ date }}</span>
      <span>🔍 {{ total_scanned }} products scanned</span>
      <span>⏱ {{ runtime }}s runtime</span>
    </div>
  </div>

  {% for p in products %}
  <div class="product-card">
    <div class="rank-badge {% if loop.index <= 3 %}top3{% endif %}">
      #{{ loop.index }}
    </div>
    {% if p.image %}
    <img class="product-img" src="{{ p.image }}" alt="{{ p.title }}" loading="lazy">
    {% else %}
    <div class="product-img-placeholder">📦</div>
    {% endif %}
    <div class="product-body">
      <p class="product-title">{{ p.title }}</p>
      <div class="scores">
        <span class="score-pill winner">🏆 {{ p.winner_score }}</span>
        <span class="score-pill demand">📈 Demand {{ p.demand_score }}</span>
        <span class="score-pill oppty">💡 Opp {{ p.opportunity_score }}</span>
        {% if p.platform == 'AliExpress' %}
        <span class="score-pill platform-ali">AliExpress</span>
        {% else %}
        <span class="score-pill platform-amz">Amazon</span>
        {% endif %}
      </div>
      <p class="breakdown">{{ p.score_breakdown }}</p>
      {% if p.url %}
      <a href="{{ p.url }}" class="cta" target="_blank">View Product →</a>
      {% endif %}
    </div>
  </div>
  {% endfor %}

  <div class="footer">
    Generated by Dropship Hunter · Automated Daily Scanner<br>
    Scores range 0–100. Winner Score = Demand×0.6 + Opportunity×0.4
  </div>
</div>
</body>
</html>
"""


class ReportEmailer:
    def __init__(self, cfg: dict):
        self.cfg = cfg["email"]

    def send(self, top_products: list[dict], total_scanned: int, runtime: float):
        today = date.today().strftime("%B %d, %Y")
        subject = self.cfg["subject"].format(date=today)

        html = Template(EMAIL_TEMPLATE).render(
            products=top_products,
            date=today,
            total_scanned=total_scanned,
            runtime=f"{runtime:.1f}",
        )

        msg = MIMEMultipart("alternative")
        msg["Subject"] = subject
        msg["From"] = self.cfg["sender"]
        msg["To"] = self.cfg["recipient"]
        msg.attach(MIMEText(html, "html"))

        try:
            with smtplib.SMTP(self.cfg["smtp_host"], self.cfg["smtp_port"]) as server:
                server.ehlo()
                server.starttls()
                server.login(self.cfg["sender"], self.cfg["app_password"])
                server.sendmail(
                    self.cfg["sender"],
                    self.cfg["recipient"],
                    msg.as_string(),
                )
            console.print(f"[green]✉  Email sent to {self.cfg['recipient']}[/green]")
        except Exception as e:
            console.print(f"[red]✗ Email failed:[/red] {e}")
            raise
